coverage:
    status:
        project:
            default:
                target: 40%
                threshold: 5%
        patch:
            default:
                target: 40%
                threshold: 5%

comment:
    layout: "header,diff,files,footer"
    behavior: default
    require_changes: false
    require_base: false
    require_head: true

github_checks:
    annotations: true
